### ISSUE TITLE
Add function to cancel selected currency

### ISSUE THREAD

**Issue by Slawbel** [Slawbel/CurrencyConverter#118]
Selected currencies could worse diagram view and user would like to remove currencies for better vision of one's currency diagram.

**Comment by Slawbel** [comment]
User should have ability to cancel already selected currency and make label on button (that opens screen with currencies) empty. 
The problem to transfer empty string from CurrencyScreen to ConverterScreen:
1) If transfer empty string in closure where usually selected currency is given to label on button in ConverterScreen then all code is failing. Also, problem to realize how to create empty string- by the second click on the row with selected currency in CurrencyScreen.
2) If transfer empty string by clicking on button "Select" in the CurrencyScreen, then we dont know which one from 4 labels on button in ConverterScreen would receive empty string. 
3) Change transfer of selected currency from closure to delegate is problem like in the second option - then code doesnt know which one from 4 labels on buttons would receive empty string.

There is one from 4 closures where label on button receives currency name from CurrencyScreen. 
![photo_2024-05-02_22-55-20](https://github.com/Slawbel/CurrencyConverter/assets/63814181/d8df4ec8-d242-432c-85df-8f9a561a1afa)

**Comment by RomanPodymov** [comment]
@Slawbel As I can see, you should rewrite your logic to "store the currency selected in didSelectRowAt in some property, then in selectButton's handler pass this value to the previous screen and then close the select currency screen".
